### PR TITLE
Macosx support

### PR DESCRIPTION
**Pull request by myselfhimself**
Github Actions support for macos x X blender 2.79*-2.8* including nightlies
2.78c is skipped for all OSes
linux x 2.79c has an extra apt-get step in Github Actions

the github actions workflow using the pip install technique out of a blender-addon-tester github url is back in place but with a nightly cron only, it is not triggered on any git push

### CODE REVIEW

**Comment by douglaskastle** [comment]
Can you reinstate all the blender options into travis?

**Comment by douglaskastle** [comment]
including 2.78, it works for me for now, so happy to keep in travis

**Comment by myselfhimself** [comment]
OK so I will try to fix 2.78c on ubuntu for github actions first..

**Comment by myselfhimself** [comment]
2.78c fixed for linux (thanks for those 2 tricks learned of manual pip download & install, and debian package retrieval for shared libraries fix)
#11 github pip install retrieval github actions workflow file added only for nightly cron. I will retarget the branch it downloads from (macosx-support) once this PR lands on master.

**Comment by douglaskastle** [comment]
can you reinstate all the blender versions back into the travis.yml? Right now it is only 2.82a

**Comment by douglaskastle** [comment]
It's Ok I have readded them myself

**Pull request merged**
